name: Deploy with Gradle

on:
  push:
    branches: [ "testing_v1" ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build and Test
      run: |
        ./gradlew spotlessApply
        ./gradlew build
        ./gradlew test
    
    - name: Create Release with JAR
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/testing_v1'
      with:
        files: build/libs/*.jar
        generate_release_notes: true
